import Crypto
import Foundation

/// Every private-key file format a person is likely to paste into this app.
///
/// The app used to accept exactly one: unencrypted `openssh-key-v1`. That is
/// what `ssh-keygen` writes by default and nothing else does. A key copied out
/// of 1Password, exported from a cloud console, or generated by `openssl`
/// arrives as PKCS#8 or PKCS#1 and was refused with a message about a format
/// the user had no way to produce.
enum PEMKeyFormat: Equatable {
    /// `-----BEGIN OPENSSH PRIVATE KEY-----`
    case openSSHV1
    /// `-----BEGIN PRIVATE KEY-----` — PKCS#8, any algorithm.
    case pkcs8
    /// `-----BEGIN RSA PRIVATE KEY-----` — PKCS#1.
    case pkcs1RSA
    /// `-----BEGIN EC PRIVATE KEY-----` — SEC 1.
    case sec1EC
    /// `-----BEGIN ENCRYPTED PRIVATE KEY-----`, or a PEM header with
    /// `Proc-Type: 4,ENCRYPTED`, or an `openssh-key-v1` with a cipher set.
    case encrypted
    /// Something else entirely — a public key, a certificate, a PuTTY `.ppk`.
    case unrecognised

    /// What a person should be told they are holding.
    var displayName: String {
        switch self {
        case .openSSHV1: return "OpenSSH private key"
        case .pkcs8: return "PKCS#8 private key"
        case .pkcs1RSA: return "PKCS#1 RSA private key"
        case .sec1EC: return "SEC 1 EC private key"
        case .encrypted: return "encrypted private key"
        case .unrecognised: return "unrecognised"
        }
    }

    var isPrivateKey: Bool { self != .unrecognised }
}

/// Reads any of the supported private-key encodings into vault key material.
enum PEMPrivateKey {
    // MARK: - Detection

    private static let markers: [(marker: String, format: PEMKeyFormat)] = [
        ("-----BEGIN ENCRYPTED PRIVATE KEY-----", .encrypted),
        ("-----BEGIN OPENSSH PRIVATE KEY-----", .openSSHV1),
        ("-----BEGIN RSA PRIVATE KEY-----", .pkcs1RSA),
        ("-----BEGIN EC PRIVATE KEY-----", .sec1EC),
        ("-----BEGIN DSA PRIVATE KEY-----", .unrecognised),
        ("-----BEGIN PRIVATE KEY-----", .pkcs8),
    ]

    /// Classify some text without parsing it.
    ///
    /// Cheap enough to run against the clipboard, which is exactly what the
    /// Keys tab does: it is how "Import key from clipboard" knows whether to
    /// offer itself at all.
    static func detect(_ text: String) -> PEMKeyFormat {
        for (marker, format) in Self.markers where text.contains(marker) {
            // A traditional PEM key carries its encryption in headers rather
            // than in the type line, so an "RSA PRIVATE KEY" can still be
            // encrypted.
            if format != .encrypted, text.contains("Proc-Type: 4,ENCRYPTED") {
                return .encrypted
            }
            if format == .openSSHV1, Self.openSSHContainerIsEncrypted(text) {
                return .encrypted
            }
            return format
        }
        return .unrecognised
    }

    /// True when `text` looks like it holds a private key of any kind.
    static func looksLikePrivateKey(_ text: String) -> Bool {
        Self.detect(text).isPrivateKey
    }

    /// An `openssh-key-v1` file names its cipher in the clear, so this does not
    /// need the passphrase to know there is one.
    private static func openSSHContainerIsEncrypted(_ text: String) -> Bool {
        guard let body = try? Self.base64Body(text, type: "OPENSSH PRIVATE KEY") else {
            return false
        }
        var reader = OpenSSHWireReader(body)
        let magic = Data("openssh-key-v1\0".utf8)
        guard reader.readBytes(magic.count) == magic,
            let cipher = reader.readStringUTF8()
        else { return false }
        return cipher != "none"
    }

    // MARK: - Parsing

    /// Parse any supported encoding.
    ///
    /// - Returns: the key material and the comment, if the format carries one
    ///   (only `openssh-key-v1` does; the others are anonymous).
    static func parse(_ text: String) throws -> (material: SSHPrivateKeyMaterial, comment: String) {
        switch Self.detect(text) {
        case .openSSHV1:
            return try OpenSSHKeyFile.parse(pem: text)
        case .pkcs8:
            return (try Self.parsePKCS8(Self.base64Body(text, type: "PRIVATE KEY")), "")
        case .pkcs1RSA:
            let der = try Self.base64Body(text, type: "RSA PRIVATE KEY")
            return (.rsa(try RSAPrivateKey(pkcs1DER: der)), "")
        case .sec1EC:
            let der = try Self.base64Body(text, type: "EC PRIVATE KEY")
            return (try Self.parseSEC1(der), "")
        case .encrypted:
            throw VaultError.encryptedKeyUnsupported
        case .unrecognised:
            throw VaultError.malformedKey(
                """
                No private key was found in that text. Ghostty reads OpenSSH keys \
                (-----BEGIN OPENSSH PRIVATE KEY-----), PKCS#8 (-----BEGIN PRIVATE KEY-----), \
                PKCS#1 RSA and SEC 1 EC keys. PuTTY .ppk files and DSA keys are not supported.
                """
            )
        }
    }

    // MARK: - PKCS#8

    /// Algorithm identifiers, as DER-encoded OBJECT IDENTIFIER contents.
    private enum OID {
        static let rsaEncryption = Data([0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x01, 0x01])
        static let ecPublicKey = Data([0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x02, 0x01])
        static let ed25519 = Data([0x2B, 0x65, 0x70])
        static let prime256v1 = Data([0x2A, 0x86, 0x48, 0xCE, 0x3D, 0x03, 0x01, 0x07])
        static let secp384r1 = Data([0x2B, 0x81, 0x04, 0x00, 0x22])
        static let secp521r1 = Data([0x2B, 0x81, 0x04, 0x00, 0x23])
    }

    /// ```
    /// PrivateKeyInfo ::= SEQUENCE {
    ///   version              INTEGER,
    ///   privateKeyAlgorithm  SEQUENCE { algorithm OBJECT IDENTIFIER, parameters ANY OPTIONAL },
    ///   privateKey           OCTET STRING }
    /// ```
    private static func parsePKCS8(_ der: Data) throws -> SSHPrivateKeyMaterial {
        var outer = DER.Reader(try DER.contents(of: .sequence, in: der))
        _ = try outer.readInteger()  // version
        var algorithm = DER.Reader(try outer.read(.sequence))
        let oid = try algorithm.read(.objectIdentifier)
        let parameters: Data? =
            algorithm.isAtEnd ? nil : try? algorithm.read(.objectIdentifier)
        let payload = try outer.read(.octetString)

        switch oid {
        case OID.rsaEncryption:
            return .rsa(try RSAPrivateKey(pkcs1DER: payload))

        case OID.ed25519:
            // RFC 8410: the OCTET STRING holds another OCTET STRING, which
            // holds the 32-byte seed. One layer of wrapping people forget.
            let seed = try DER.contents(of: .octetString, in: payload)
            guard seed.count == 32 else {
                throw VaultError.malformedKey(
                    "An Ed25519 seed should be 32 bytes; this one is \(seed.count)."
                )
            }
            guard let key = try? Curve25519.Signing.PrivateKey(rawRepresentation: seed) else {
                throw VaultError.malformedKey("The Ed25519 private scalar is invalid.")
            }
            return .ed25519(key)

        case OID.ecPublicKey:
            // The payload is a SEC 1 ECPrivateKey; the curve may be named
            // there or in the algorithm parameters, so pass ours down as the
            // fallback.
            return try Self.parseSEC1(payload, curveOID: parameters)

        default:
            throw VaultError.unsupportedKeyType(Self.name(forOID: oid))
        }
    }

    // MARK: - SEC 1

    /// ```
    /// ECPrivateKey ::= SEQUENCE {
    ///   version        INTEGER (1),
    ///   privateKey     OCTET STRING,
    ///   parameters [0] ECParameters OPTIONAL,
    ///   publicKey  [1] BIT STRING   OPTIONAL }
    /// ```
    private static func parseSEC1(_ der: Data, curveOID: Data? = nil) throws -> SSHPrivateKeyMaterial {
        var reader = DER.Reader(try DER.contents(of: .sequence, in: der))
        _ = try reader.readInteger()  // version, always 1
        let scalar = try reader.read(.octetString)

        // [0] parameters, a context-specific constructed tag holding the
        // curve OID. Optional here, because PKCS#8 may have named the curve in
        // the algorithm identifier instead.
        var oid = curveOID
        if reader.peekTag() == 0xA0, let wrapper = try? reader.readAny().contents {
            oid = try? DER.contents(of: .objectIdentifier, in: wrapper)
        }

        guard let oid else {
            throw VaultError.malformedKey("The EC key does not say which curve it is on.")
        }

        let type: SSHKeyType
        switch oid {
        case OID.prime256v1: type = .p256
        case OID.secp384r1: type = .p384
        case OID.secp521r1: type = .p521
        default: throw VaultError.unsupportedKeyType(Self.name(forOID: oid))
        }

        // The scalar is fixed width in SEC 1, but a leading zero byte is legal
        // and some encoders emit a short one; normalise before CryptoKit sees it.
        let width = type == .p256 ? 32 : (type == .p384 ? 48 : 66)
        guard let normalised = OpenSSHWire.mpintToFixedWidth(scalar, byteCount: width) else {
            throw VaultError.malformedKey(
                "The EC private scalar is \(scalar.count) bytes; \(type.displayName) needs \(width)."
            )
        }

        do {
            switch type {
            case .p256: return .p256(try P256.Signing.PrivateKey(rawRepresentation: normalised))
            case .p384: return .p384(try P384.Signing.PrivateKey(rawRepresentation: normalised))
            case .p521: return .p521(try P521.Signing.PrivateKey(rawRepresentation: normalised))
            default: throw VaultError.unsupportedKeyType(type.opensshName)
            }
        } catch let error as VaultError {
            throw error
        } catch {
            throw VaultError.malformedKey(
                "The scalar is not a valid \(type.displayName) private key."
            )
        }
    }

    // MARK: - PEM framing

    /// Pull the base64 body out of a PEM block, tolerating the things that
    /// happen to a key on its way through a clipboard: leading whitespace,
    /// CRLF line endings, and trailing junk after the END line.
    static func base64Body(_ text: String, type: String) throws -> Data {
        let begin = "-----BEGIN \(type)-----"
        let end = "-----END \(type)-----"
        let lines = text.split(whereSeparator: \.isNewline).map {
            $0.trimmingCharacters(in: .whitespaces)
        }
        guard let first = lines.firstIndex(of: begin),
            let last = lines.lastIndex(of: end),
            first < last
        else {
            throw VaultError.malformedKey("Expected a block starting with \"\(begin)\".")
        }
        // Traditional PEM encryption headers sit between BEGIN and the body,
        // separated by a blank line.
        var body = lines[(first + 1)..<last]
        if let blank = body.firstIndex(of: "") {
            body = body[(blank + 1)...]
        }
        let joined = body.filter { !$0.contains(":") }.joined()
        guard !joined.isEmpty, let data = Data(base64Encoded: joined) else {
            throw VaultError.malformedKey("The base64 body is empty or not decodable.")
        }
        return data
    }

    /// Dotted-decimal for an OID we do not handle, so the error names the thing
    /// the user actually has.
    private static func name(forOID oid: Data) -> String {
        guard let first = oid.first else { return "an unknown algorithm" }
        var parts = [String(first / 40), String(first % 40)]
        var value = 0
        for byte in oid.dropFirst() {
            value = (value << 7) | Int(byte & 0x7F)
            if byte & 0x80 == 0 {
                parts.append(String(value))
                value = 0
            }
        }
        return parts.joined(separator: ".")
    }
}
