import Crypto
import UIKit
import Foundation
import NIOSSH
import XCTest

@testable import Ghostty

/// Format detection and the four private-key encodings people actually have.
///
/// Before this, the app accepted exactly one — unencrypted `openssh-key-v1` —
/// which is what `ssh-keygen` writes and nothing else does. A key copied out of
/// 1Password, exported from a cloud console or generated by `openssl` arrives
/// as PKCS#8 or PKCS#1 and was refused with a message naming a format the user
/// had no way to produce (#008A1).
final class PEMKeyFormatDetectionTests: XCTestCase {
    func testDetectsEveryFormatItAccepts() {
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.rsaPKCS1), .pkcs1RSA)
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.rsaPKCS8), .pkcs8)
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.ecSEC1), .sec1EC)
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.ecPKCS8), .pkcs8)
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.ed25519PKCS8), .pkcs8)
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.openSSHRSA), .openSSHV1)
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.openSSHEd25519), .openSSHV1)
    }

    func testDetectsEncryptedKeysWithoutThePassphrase() {
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.encryptedPKCS8), .encrypted)
        // Traditional PEM carries its encryption in a header rather than in the
        // type line, so an "RSA PRIVATE KEY" can still be encrypted.
        let traditional = """
            -----BEGIN RSA PRIVATE KEY-----
            Proc-Type: 4,ENCRYPTED
            DEK-Info: AES-128-CBC,0123456789ABCDEF

            AAAA
            -----END RSA PRIVATE KEY-----
            """
        XCTAssertEqual(PEMPrivateKey.detect(traditional), .encrypted)
    }

    func testRejectsThingsThatAreNotPrivateKeys() {
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.puttyPPK), .unrecognised)
        XCTAssertEqual(PEMPrivateKey.detect(KeyFormatFixtures.openSSHRSAPublicLine), .unrecognised)
        XCTAssertEqual(PEMPrivateKey.detect("just some text"), .unrecognised)
        XCTAssertEqual(PEMPrivateKey.detect(""), .unrecognised)
    }

    /// The clipboard check the Keys tab runs. It must be true for a key and
    /// false for anything else, because a false positive offers to import the
    /// user's shopping list.
    func testLooksLikePrivateKeyIsTheClipboardTest() {
        XCTAssertTrue(PEMPrivateKey.looksLikePrivateKey(KeyFormatFixtures.rsaPKCS8))
        XCTAssertTrue(PEMPrivateKey.looksLikePrivateKey(KeyFormatFixtures.encryptedPKCS8))
        XCTAssertFalse(PEMPrivateKey.looksLikePrivateKey("https://example.com"))
        XCTAssertFalse(PEMPrivateKey.looksLikePrivateKey(KeyFormatFixtures.puttyPPK))
    }

    /// A key that has been through a clipboard picks up whitespace and CRLFs.
    func testToleratesWhatAClipboardDoesToAKey() throws {
        let mangled =
            "\n\n  "
            + KeyFormatFixtures.ed25519PKCS8.replacingOccurrences(of: "\n", with: "\r\n")
            + "\n\n"
        XCTAssertEqual(PEMPrivateKey.detect(mangled), .pkcs8)
        let parsed = try PEMPrivateKey.parse(mangled)
        XCTAssertEqual(parsed.material.keyType, .ed25519)
    }

    func testAnEncryptedKeySaysHowToDecryptIt() {
        XCTAssertThrowsError(try PEMPrivateKey.parse(KeyFormatFixtures.encryptedPKCS8)) { error in
            XCTAssertEqual(error as? VaultError, .encryptedKeyUnsupported)
            XCTAssertTrue(
                (error as? VaultError)?.errorDescription?.contains("ssh-keygen -p") == true,
                "the error has to carry the command that fixes it"
            )
        }
    }

    func testAnUnrecognisedFormatNamesWhatIsSupported() {
        XCTAssertThrowsError(try PEMPrivateKey.parse(KeyFormatFixtures.puttyPPK)) { error in
            let text = (error as? VaultError)?.errorDescription ?? ""
            XCTAssertTrue(text.contains("PKCS#8"))
            XCTAssertTrue(text.contains("PuTTY"))
        }
    }
}

final class PEMKeyParsingTests: XCTestCase {
    func testParsesPKCS8Ed25519() throws {
        let parsed = try PEMPrivateKey.parse(KeyFormatFixtures.ed25519PKCS8)
        XCTAssertEqual(parsed.material.keyType, .ed25519)
        // The public half has to be derivable, which is the real check that the
        // seed came out of the right layer of OCTET STRING wrapping.
        XCTAssertTrue(parsed.material.publicKeyLine(comment: "x").hasPrefix("ssh-ed25519 AAAA"))
    }

    /// The same EC key in both encodings must produce the same key. This is the
    /// test that catches a scalar read from the wrong field.
    func testSEC1AndPKCS8AgreeForTheSameECKey() throws {
        let sec1 = try PEMPrivateKey.parse(KeyFormatFixtures.ecSEC1)
        let pkcs8 = try PEMPrivateKey.parse(KeyFormatFixtures.ecPKCS8)
        XCTAssertEqual(sec1.material.keyType, .p256)
        XCTAssertEqual(pkcs8.material.keyType, .p256)
        XCTAssertEqual(sec1.material.fingerprint, pkcs8.material.fingerprint)
        XCTAssertEqual(sec1.material.fingerprint, KeyFormatFixtures.ecFingerprint)
    }

    func testParsesPKCS1AndPKCS8RSA() throws {
        let pkcs1 = try PEMPrivateKey.parse(KeyFormatFixtures.rsaPKCS1)
        XCTAssertEqual(pkcs1.material.keyType, .rsa)
        XCTAssertEqual(pkcs1.material.fingerprint, KeyFormatFixtures.rsaPKCS1Fingerprint)

        let pkcs8 = try PEMPrivateKey.parse(KeyFormatFixtures.rsaPKCS8)
        XCTAssertEqual(pkcs8.material.keyType, .rsa)
        XCTAssertEqual(pkcs8.material.fingerprint, KeyFormatFixtures.rsaPKCS8Fingerprint)
    }

    /// `ssh-keygen -t rsa` writes `openssh-key-v1`, which stores n, e, d, iqmp,
    /// p and q but *not* the CRT exponents PKCS#1 needs. Getting this right is
    /// the whole reason `BigUnsignedInteger` exists.
    func testParsesAnOpenSSHRSAKeyByRecomputingItsCRTExponents() throws {
        let parsed = try PEMPrivateKey.parse(KeyFormatFixtures.openSSHRSA)
        XCTAssertEqual(parsed.material.keyType, .rsa)
        XCTAssertEqual(parsed.material.fingerprint, KeyFormatFixtures.openSSHRSAFingerprint)
        XCTAssertEqual(parsed.comment, "andrewhaynes@sagan")

        // The public line must match byte for byte what `ssh-keygen -y` prints.
        XCTAssertEqual(
            parsed.material.publicKeyLine(comment: parsed.comment),
            KeyFormatFixtures.openSSHRSAPublicLine
        )

        // And the rebuilt key must actually work: Security.framework only hands
        // back a usable SecKey if the CRT exponents are consistent.
        guard case .rsa(let key) = parsed.material else { return XCTFail("expected an RSA key") }
        let message = Data("round trip".utf8)
        let signature = try key.signature(for: message, algorithm: .sha256)
        XCTAssertTrue(
            key.publicKey.isValidSignature(signature, for: message, algorithm: .sha256)
        )
    }

    func testOpenSSHRoundTripsRSAThroughItsOwnContainer() throws {
        let parsed = try PEMPrivateKey.parse(KeyFormatFixtures.openSSHRSA)
        let encoded = try OpenSSHKeyFile.encode(material: parsed.material, comment: "again")
        let reparsed = try OpenSSHKeyFile.parse(pem: encoded)
        XCTAssertEqual(reparsed.material.fingerprint, parsed.material.fingerprint)
        XCTAssertEqual(reparsed.comment, "again")
    }
}

/// RSA itself: the wire format, the fingerprint, and signatures.
final class RSAKeyTests: XCTestCase {
    private func rsaKey(_ pem: String) throws -> RSAPrivateKey {
        guard case .rsa(let key) = try PEMPrivateKey.parse(pem).material else {
            throw XCTSkip("not an RSA key")
        }
        return key
    }

    /// Verify against signatures produced by `openssl` on the Mac and committed
    /// as fixtures. Our own signature verifying against our own public key
    /// proves only that we are self-consistent.
    func testVerifiesSignaturesMadeByOpenSSL() throws {
        let key = try rsaKey(KeyFormatFixtures.rsaPKCS1)
        let message = Data(KeyFormatFixtures.signedMessage.utf8)

        let sha256 = try XCTUnwrap(
            Data(base64Encoded: KeyFormatFixtures.rsaSignatureSHA256, options: .ignoreUnknownCharacters)
        )
        XCTAssertTrue(
            key.publicKey.isValidSignature(sha256, for: message, algorithm: .sha256),
            "rsa-sha2-256 signature from openssl must verify"
        )

        let sha512 = try XCTUnwrap(
            Data(base64Encoded: KeyFormatFixtures.rsaSignatureSHA512, options: .ignoreUnknownCharacters)
        )
        XCTAssertTrue(
            key.publicKey.isValidSignature(sha512, for: message, algorithm: .sha512),
            "rsa-sha2-512 signature from openssl must verify"
        )

        // Right signature, wrong hash: must not verify.
        XCTAssertFalse(key.publicKey.isValidSignature(sha256, for: message, algorithm: .sha512))
        // Right signature, wrong message.
        XCTAssertFalse(
            key.publicKey.isValidSignature(sha256, for: Data("other".utf8), algorithm: .sha256)
        )
    }

    func testSignsAndVerifies() throws {
        let key = try rsaKey(KeyFormatFixtures.rsaPKCS1)
        let message = Data("sign me".utf8)
        for algorithm in [RSASignatureAlgorithm.sha256, .sha512] {
            let signature = try key.signature(for: message, algorithm: algorithm)
            XCTAssertTrue(key.publicKey.isValidSignature(signature, for: message, algorithm: algorithm))
        }
    }

    /// SHA-1 is readable but never produced.
    func testRefusesToProduceAnSSHRSASignature() throws {
        let key = try rsaKey(KeyFormatFixtures.rsaPKCS1)
        XCTAssertFalse(RSASignatureAlgorithm.sshRSA.isUsableForSigning)
        XCTAssertThrowsError(try key.signature(for: Data("x".utf8), algorithm: .sshRSA))
    }

    /// `string("ssh-rsa") || mpint(e) || mpint(n)` — exponent first, which is
    /// the opposite of every other encoding RSA appears in.
    func testWireFormatRoundTripsAndKeepsTheFieldOrder() throws {
        let key = try rsaKey(KeyFormatFixtures.rsaPKCS1)
        let blob = key.publicKey.sshBlob

        var reader = OpenSSHWireReader(blob)
        XCTAssertEqual(reader.readStringUTF8(), "ssh-rsa")
        let e = try XCTUnwrap(reader.readString())
        let n = try XCTUnwrap(reader.readString())
        XCTAssertLessThan(e.count, n.count, "the exponent comes first")

        let reparsed = try RSAPublicKey(sshBlob: blob)
        XCTAssertEqual(reparsed.modulus, key.publicKey.modulus)
        XCTAssertEqual(reparsed.exponent, key.publicKey.exponent)
        XCTAssertEqual(reparsed.fingerprint, KeyFormatFixtures.rsaPKCS1Fingerprint)
    }

    func testParsesARealServerHostKeyLine() throws {
        // `rsa-sha2-256` and `rsa-sha2-512` name a *signature* algorithm; the
        // key blob still says "ssh-rsa" (RFC 8332 §3). A parser that keys off
        // the negotiated name rejects perfectly good host keys.
        let fields = KeyFormatFixtures.openSSHRSAPublicLine.split(separator: " ")
        let blob = try XCTUnwrap(Data(base64Encoded: String(fields[1])))
        let key = try RSAPublicKey(sshBlob: blob)
        XCTAssertEqual(key.fingerprint, KeyFormatFixtures.openSSHRSAFingerprint)
        XCTAssertEqual(key.bitCount, 2048)
    }

    func testRejectsAnUndersizedModulus() {
        XCTAssertThrowsError(
            try RSAPublicKey(modulus: Data(repeating: 0xFF, count: 64), exponent: Data([1, 0, 1]))
        ) { error in
            XCTAssertEqual(error as? RSAKeyError, .unsupportedKeySize(512))
        }
    }

    func testRejectsANonRSABlob() throws {
        let blob = OpenSSHWire.writeString("ssh-ed25519") + OpenSSHWire.writeString(Data(repeating: 1, count: 32))
        XCTAssertThrowsError(try RSAPublicKey(sshBlob: blob))
    }
}

/// The two big-integer operations rebuilding an OpenSSH RSA key needs.
final class BigUnsignedIntegerTests: XCTestCase {
    func testDecrementBorrowsAcrossBytes() {
        XCTAssertEqual(BigUnsignedInteger.decrement(Data([0x01, 0x00])), Data([0xFF]))
        XCTAssertEqual(BigUnsignedInteger.decrement(Data([0x05])), Data([0x04]))
        XCTAssertEqual(
            BigUnsignedInteger.decrement(Data([0x01, 0x00, 0x00, 0x00])),
            Data([0xFF, 0xFF, 0xFF])
        )
        XCTAssertNil(BigUnsignedInteger.decrement(Data([0x00, 0x00])))
    }

    func testModuloMatchesArithmeticOnValuesSmallEnoughToCheck() {
        for dividend in [0, 1, 7, 255, 256, 65_535, 1_000_003] {
            for divisor in [1, 2, 3, 7, 251, 65_521] {
                let result = BigUnsignedInteger.modulo(
                    Self.bytes(dividend),
                    Self.bytes(divisor)
                )
                XCTAssertEqual(
                    Self.value(try! XCTUnwrap(result)),
                    dividend % divisor,
                    "\(dividend) mod \(divisor)"
                )
            }
        }
    }

    func testModuloOfALargeNumber() {
        // 2^256 mod (2^128 - 1) == 1, which is easy to state and hard to get
        // right by accident.
        var dividend = [UInt8](repeating: 0, count: 33)
        dividend[0] = 1
        let divisor = [UInt8](repeating: 0xFF, count: 16)
        let result = BigUnsignedInteger.modulo(Data(dividend), Data(divisor))
        XCTAssertEqual(result, Data([1]))
    }

    func testModuloByZeroIsRefused() {
        XCTAssertNil(BigUnsignedInteger.modulo(Data([1, 2, 3]), Data([0, 0])))
    }

    private static func bytes(_ value: Int) -> Data {
        var remaining = value
        var out: [UInt8] = []
        repeat {
            out.insert(UInt8(remaining & 0xFF), at: 0)
            remaining >>= 8
        } while remaining > 0
        return Data(out)
    }

    private static func value(_ data: Data) -> Int {
        data.reduce(0) { ($0 << 8) | Int($1) }
    }
}

/// Importing a key the way a person actually gets one onto a phone: out of
/// 1Password, through the clipboard, into the vault (#008A1).
@MainActor
final class ClipboardKeyImportTests: XCTestCase {
    private func makeVault() -> Vault {
        Vault(
            keychain: InMemoryKeychain(),
            directory: FileManager.default.temporaryDirectory
                .appendingPathComponent("ghostty-clip-\(UUID().uuidString)", isDirectory: true)
        )
    }

    override func tearDown() {
        UIPasteboard.general.items = []
        super.tearDown()
    }

    func testReadsAKeyOffTheClipboardAndSuggestsItsComment() {
        UIPasteboard.general.string = KeyFormatFixtures.openSSHRSA
        XCTAssertTrue(ClipboardKeyImport.mayHaveKey)

        guard case .key(let text, let format, let suggested) = ClipboardKeyImport.read() else {
            return XCTFail("expected a key")
        }
        XCTAssertEqual(format, .openSSHV1)
        XCTAssertEqual(suggested, "andrewhaynes@sagan", "the key's own comment is the best name")
        XCTAssertEqual(text, KeyFormatFixtures.openSSHRSA)
    }

    /// PKCS#8 — what 1Password actually hands out — carries no comment, so the
    /// suggestion has to be a placeholder rather than an empty field.
    func testSuggestsAPlaceholderNameForAnAnonymousFormat() {
        UIPasteboard.general.string = KeyFormatFixtures.rsaPKCS8
        guard case .key(_, let format, let suggested) = ClipboardKeyImport.read() else {
            return XCTFail("expected a key")
        }
        XCTAssertEqual(format, .pkcs8)
        XCTAssertFalse(suggested.isEmpty)
    }

    func testDistinguishesEncryptedAndNonKeyClipboards() {
        UIPasteboard.general.string = KeyFormatFixtures.encryptedPKCS8
        guard case .encryptedKey = ClipboardKeyImport.read() else {
            return XCTFail("an encrypted key must be reported as such, not as a key")
        }

        UIPasteboard.general.string = "https://example.com/not-a-key"
        guard case .notAKey = ClipboardKeyImport.read() else {
            return XCTFail("a URL is not a key")
        }

        UIPasteboard.general.items = []
        guard case .empty = ClipboardKeyImport.read() else {
            return XCTFail("an empty clipboard is empty")
        }
        XCTAssertFalse(ClipboardKeyImport.mayHaveKey)
    }

    /// A public key on the clipboard is the most likely wrong thing to copy,
    /// and it must not look like a private one.
    func testAPublicKeyIsNotOfferedForImport() {
        UIPasteboard.general.string = KeyFormatFixtures.openSSHRSAPublicLine
        guard case .notAKey = ClipboardKeyImport.read() else {
            return XCTFail("a public key line is not a private key")
        }
    }

    func testClearingTheClipboardLeavesNothingBehind() {
        UIPasteboard.general.string = KeyFormatFixtures.rsaPKCS8
        XCTAssertTrue(ClipboardKeyImport.mayHaveKey)
        ClipboardKeyImport.clear()
        XCTAssertFalse(ClipboardKeyImport.mayHaveKey)
        XCTAssertNil(UIPasteboard.general.string)
    }

    /// Every format the clipboard path accepts must reach the vault, keep its
    /// fingerprint, and come back out as an `authorized_keys` line.
    func testImportsEveryFormatIntoTheVault() throws {
        let cases: [(String, String, SSHKeyType)] = [
            (KeyFormatFixtures.ed25519PKCS8, "ed-pkcs8", .ed25519),
            (KeyFormatFixtures.ecSEC1, "ec-sec1", .p256),
            (KeyFormatFixtures.ecPKCS8, "ec-pkcs8", .p256),
            (KeyFormatFixtures.rsaPKCS1, "rsa-pkcs1", .rsa),
            (KeyFormatFixtures.rsaPKCS8, "rsa-pkcs8", .rsa),
            (KeyFormatFixtures.openSSHRSA, "rsa-openssh", .rsa),
        ]
        let vault = makeVault()
        for (pem, name, expected) in cases {
            let identity = try vault.importIdentity(name: name, pem: pem)
            XCTAssertEqual(identity.keyType, expected, name)
            XCTAssertTrue(identity.fingerprint.hasPrefix("SHA256:"), name)
            XCTAssertTrue(
                identity.publicKeyLine.hasPrefix(expected.opensshName),
                "\(name) should export a \(expected.opensshName) line"
            )
            // And it must survive a Keychain round trip.
            let restored = try vault.privateKey(for: identity)
            XCTAssertEqual(restored.fingerprint, identity.fingerprint, name)
        }
        XCTAssertEqual(vault.identities.count, cases.count)
    }

    /// An imported RSA key can now open a connection (#008D0), which it could
    /// not before the swift-nio-ssh fork. The seam is
    /// `SSHPrivateKeyMaterial.nioSSHPrivateKey()`, so that is what is asserted:
    /// a fingerprint and an exported line were never the missing part.
    func testAnRSAIdentityCanAuthenticate() throws {
        let vault = makeVault()
        let identity = try vault.importIdentity(name: "rsa", pem: KeyFormatFixtures.rsaPKCS8)
        XCTAssertTrue(identity.keyType.canAuthenticate)

        let material = try vault.privateKey(for: identity)
        let nioKey = try material.nioSSHPrivateKey()

        // The public half NIOSSH derives has to be the same key the vault
        // exported, or the server would be handed a line that does not match
        // the signature it then has to verify.
        XCTAssertEqual(
            String(openSSHPublicKey: nioKey.publicKey),
            identity.publicKeyLine.split(separator: " ").prefix(2).joined(separator: " ")
        )

        // And the offer really carries that key, rather than falling through to
        // "no credential" the way it used to.
        let offer = try material.authenticationOffer(username: "andy")
        guard case .privateKey(let privateKeyOffer) = offer.offer else {
            return XCTFail("an RSA key should produce a private key offer")
        }
        XCTAssertEqual(privateKeyOffer.publicKey, nioKey.publicKey)
    }

    func testRSAIsStillNotOfferedAsAKeyToGenerate() throws {
        XCTAssertFalse(
            SSHKeyType.generatable.contains(.rsa),
            "RSA works, but nobody should be nudged into generating a new one in 2026"
        )
    }
}
